---
title: "Data Manipulation"
author: "Ford Holland"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Import data

```{r}
# read dataset
litters_data = read_csv("Data/FAS_litters.csv")
pups_data = read_csv("Data/FAS_pups.csv")

litters_data <- janitor::clean_names(litters_data)
pups_data <- janitor::clean_names(pups_data)


# clean names
litters_data = janitor::clean_names(litters_data)

# view data
glimpse(litters_data)

# brief summary
skimr::skim(litters_data)

```


## Selecting

```{r}
litters_data %>% 
  select(litter_number, starts_with("pups"))

# arange
litters_data %>%
  select(litter_number, everything())

litters_data %>% 
  select(litter_number, gd0_weight:pups_born_alive)

litters_data %>% 
  select(-group)

# rename
litters_data %>% 
  select(GROUP = group)

```


## Filtering
```{r}
litters_data %>% 
  filter(group == "Con7")

# can separateconditions by comma
litters_data %>% 
  filter(group == "Con7", 
         pups_born_alive > 2)

# dont filter !is.na()
# use drop_na
litters_data %>% 
  drop_na(gd0_weight)
```





```{r}
# test contains()
# temp <- as.character(1:100)
# 
# contains("5", temp)
```



## Mutate

```{r}
litters_data %>% 
  mutate(wt_gain = gd18_weight - gd0_weight,
         group = group %>% str_to_lower())

```


## Arrange

```{r}
litters_data %>% 
  arrange(desc(pups_born_alive))
```


## Pipe

create a collection of commands

```{r}
litters_data = 
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)) %>% 
  drop_na(wt_gain)

litters_data

# . is last thing that happened in chain of commands
# this is how you pipe when the fist arg id not data, like grepl
ex = 
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names(dat = .) %>% 
  lm(gd0_weight ~ gd18_weight, data = .)
```


